name: Build and Deploy to cloudhub
on:
  push:
    branches: [main]
  workflow_dispatch: 
jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: maven-settings-xml-action
      env: 
        ORG_ID: ${{ secrets.ORG_ID }}
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: >
           [
              {
                "id": "maven-central",
                "name": "Maven Central Repository",
                "url": "https://repo1.maven.org/maven2/",
                "layout": "default",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true"
                }
              },
              {
                "id": "mulesoft-releases",
                "name": "MuleSoft Releases Repository",
                "url": "http://repository.mulesoft.org/releases/",
                "layout": "default",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true"
                }
              },
              {
                "id": "mulesoft-releases-ee",
                "name": "MuleSoft Enterprise Releases Repository",
                "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/",
                "layout": "default",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true"
                }
              },
              {
                "id": "mulesoft-public",
                "name": "MuleSoft Public Repository",
                "url": "https://repository.mulesoft.org/nexus/content/repositories/public",
                "layout": "default",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              },
              {
                "id": "Exchange",
                "name": "anypoint.exchange.repository",
                "url": "https://maven.anypoint.mulesoft.com/api/v3/maven",
                "layout": "default",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true"
                }
              },
              {
                "id": "anypoint-exchange-v2",
                "name": "anypoint.exchange.repository",
                "url": "https://maven.anypoint.mulesoft.com/api/v3/maven",
                "layout": "default",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true"
                }
              },
              {
                "id": "anypoint-exchange",
                "name": "Corporate Anypoint Exchange",
                "url": "https://maven.anypoint.mulesoft.com/api/v1/organizations/${{env.ORG_ID}}/maven/",
                "layout": "default",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true"
                }
              }
            ]
        servers: >
          [
              {
                "id": "Exchange",
                "username": "${{secrets.M_USERNAME}}",
                "password": "${{secrets.M_PASSWORD}}"
              },
              {
                "id": "anypoint-exchange",
                "username": "${{secrets.M_USERNAME}}",
                "password": "${{secrets.M_PASSWORD}}"
              },
              {
                "id": "anypoint-exchange-v2",
                "username": "${{secrets.M_USERNAME}}",
                "password": "${{secrets.M_PASSWORD}}"
              },
              {
                "id": "Exchange2",
                "username": "${{secrets.M_USERNAME}}",
                "password": "${{secrets.M_PASSWORD}}"
              },
              {
                "id": "mulesoft-releases",
                "username": "${{secrets.M_USERNAME}}",
                "password": "${{secrets.M_PASSWORD}}"
              },
              {
                "id": "mulesoft-snapshots",
                "username": "${{secrets.M_USERNAME}}",
                "password": "${{secrets.M_PASSWORD}}"
              },
              {
                "id": "mulesoft-releases-ee",
                "username": "${{secrets.M_USERNAME}}",
                "password": "${{secrets.M_PASSWORD}}"
              }
          ]
        profiles: >
          [
              {
                "id": "global-settings",
                "properties": {
                  "anypoint.org.id": "${{env.ORG_ID}}",
                  "anypoint.exchange.repository": "https://maven.anypoint.mulesoft.com/api/v3/maven"
                }
              }
          ]
        plugin_repositories: >
          [
              {
                "id": "mulesoft-releases",
                "name": "mulesoft release repository",
                "layout": "default",
                "url": "https://repository.mulesoft.org/releases/",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true"
                }
              },
              {
                "id": "mule-public",
                "url": "https://repository.mulesoft.org/nexus/content/repositories/public"
              }
          ]
    - name: Print effective-settings (optional)
      run: mvn help:effective-settings
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.test.skip=true
      
    - name: Stamp artifact file name with commit hash
      run: |
        artifactName1=$(ls target/*.jar | head -1)
        commitHash=$(git rev-parse --short "$GITHUB_SHA")
        artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g")
        mv $artifactName1 $artifactName2
    - name: Upload artifact 
      uses: actions/upload-artifact@master
      with:
          name: artifacts
          path: target/*.jar
    
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:    
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        env: 
          ORG_ID: ${{ secrets.ORG_ID }}
        with:
          repositories: >
            [
              {
                "id": "maven-central",
                "name": "Maven Central Repository",
                "url": "https://repo1.maven.org/maven2/",
                "layout": "default",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true"
                }
              },
              {
                "id": "mulesoft-releases",
                "name": "MuleSoft Releases Repository",
                "url": "http://repository.mulesoft.org/releases/",
                "layout": "default",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true"
                }
              },
              {
                "id": "mulesoft-releases-ee",
                "name": "MuleSoft Enterprise Releases Repository",
                "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/",
                "layout": "default",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true"
                }
              },
              {
                "id": "mulesoft-public",
                "name": "MuleSoft Public Repository",
                "url": "https://repository.mulesoft.org/nexus/content/repositories/public",
                "layout": "default",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              },
              {
                "id": "Exchange",
                "name": "anypoint.exchange.repository",
                "url": "https://maven.anypoint.mulesoft.com/api/v3/maven",
                "layout": "default",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true"
                }
              },
              {
                "id": "anypoint-exchange-v2",
                "name": "anypoint.exchange.repository",
                "url": "https://maven.anypoint.mulesoft.com/api/v3/maven",
                "layout": "default",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true"
                }
              },
              {
                "id": "anypoint-exchange",
                "name": "Corporate Anypoint Exchange",
                "url": "https://maven.anypoint.mulesoft.com/api/v1/organizations/${{env.ORG_ID}}/maven/",
                "layout": "default",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true"
                }
              }
            ]
          servers: >
            [
              {
                "id": "Exchange",
                "username": "${{secrets.M_USERNAME}}",
                "password": "${{secrets.M_PASSWORD}}"
              },
              {
                "id": "anypoint-exchange",
                "username": "${{secrets.M_USERNAME}}",
                "password": "${{secrets.M_PASSWORD}}"
              },
              {
                "id": "anypoint-exchange-v2",
                "username": "${{secrets.M_USERNAME}}",
                "password": "${{secrets.M_PASSWORD}}"
              },
              {
                "id": "Exchange2",
                "username": "${{secrets.M_USERNAME}}",
                "password": "${{secrets.M_PASSWORD}}"
              },
              {
                "id": "mulesoft-releases",
                "username": "${{secrets.M_USERNAME}}",
                "password": "${{secrets.M_PASSWORD}}"
              },
              {
                "id": "mulesoft-snapshots",
                "username": "${{secrets.M_USERNAME}}",
                "password": "${{secrets.M_PASSWORD}}"
              },
              {
                "id": "mulesoft-releases-ee",
                "username": "${{secrets.M_USERNAME}}",
                "password": "${{secrets.M_PASSWORD}}"
              }
            ]
          profiles: >
            [
              {
                "id": "global-settings",
                "properties": {
                  "anypoint.org.id": "${{env.ORG_ID}}",
                  "anypoint.exchange.repository": "https://maven.anypoint.mulesoft.com/api/v3/maven"
                }
              }
            ]
          plugin_repositories: >
            [
              {
                "id": "mulesoft-releases",
                "name": "mulesoft release repository",
                "layout": "default",
                "url": "https://repository.mulesoft.org/releases/",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true"
                }
              },
              {
                "id": "mule-public",
                "url": "https://repository.mulesoft.org/nexus/content/repositories/public"
              }
            ]
      - uses: actions/download-artifact@master
        with:
          name: artifacts

      - name: Deploy to Sandbox
        env:
          USERNAME: ${{ secrets.M_USERNAME }}
          PASSWORD: ${{ secrets.M_PASSWORD }}
        run: |
          artifactName=$(ls *.jar | head -1)
          mvn deploy -DmuleDeploy \
          -Dmule.artifact=$artifactName \
          -Danypoint.username="$USERNAME" \
          -Danypoint.password="$PASSWORD" \
          -Dmaven.test.skip=true
